Oakにしました
kakomimasu/server pull request #123
Opened 2022-01-07 13:40 UTC by ninja03

2022-01-08 08:44 UTC, kamekyame commented
@ninja03 上記の2点について修正お願いしてもよいでしょうか？

2022-01-10 09:22 UTC, ninja03 commented
テストが直らなくて困ってます

2022-01-10 10:09 UTC, kamekyame commented
テストは僕も見てみましたが、よくわからないですね...
もうちょっと調査してみます。

2022-01-10 10:23 UTC, kamekyame requested changes
レビューの内容が送られてないみたいでした🙇
この3点について修正お願いします。

2022-01-10 10:23 UTC, kamekyame commented on v1/match.ts
> +    auth({ bearer: true }),
@ninja03 テストが通らないのは、ここにauthチェックが入っているからだと思います。これを抜くと通ると思います。

2022-01-10 12:50 UTC, ninja03 commented
テスト動きました！
ありがとうございます

2022-01-10 13:01 UTC, kamekyame approved these changes
LGTM:+1:

2022-01-10 13:01 UTC, merged